version: "3.5"


services:


    pgweb:
        image: sosedoff/pgweb
        restart: always
        ports:
            - "8082:8081"
        environment:
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}?sslmode=disable
        networks:
            - db
        depends_on:
            - db


    front:
        build:
            context: .
            dockerfile: front.dockerfile
        image: front_nuxt
        ports:
            - "8081:3000"
        environment:
            BACKEND_URL: ${BACKEND_URL}


    api:
        depends_on:
            - db
        build:
            context: .
            dockerfile: api.dockerfile
            target: api
        image: fastapi
        volumes:
            - db-revision:/app/backend/db/migrations/versions
        environment:
            PSQL_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
            COOKIE_DOMAIN: ${COOKIE_DOMAIN}
        networks:
            - db
        ports:
            - "8080:80"
        depends_on:
            - db
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"


    db:
        image: postgres:13-alpine
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        command: postgres -c 'max_connections=500'
        networks:
            - db
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"

networks:
    db:
    
volumes:
    db-data:
    db-revision: